Code cleanups for Python 3 and Django > 2.2
django-treebeard/django-treebeard pull request #183
Opened 2020-10-24 05:56 UTC by solarissmoke

- Use simplified `super()` calls now that we've dropped Python 2 support.
- Replace use of deprecated `django.conf.urls.url` with `django.urls.path`.

2020-10-24 11:49 UTC, hartwork reviewed
From a quick look, this looks good to me.

Probably the right time to add `python_requires='>=3.6'` to `setup.py` as well?

2020-10-25 03:43 UTC, solarissmoke commented
> Probably the right time to add `python_requires='>=3.6'` to setup.py as well?

Yep - done.

2020-10-25 12:59 UTC, hartwork requested changes
I found one `super` left to fix: https://github.com/django-treebeard/django-treebeard/blob/47e734236614f6637b752cc35c07dbd9c99af471/treebeard/mp_tree.py#L124

2020-10-25 13:04 UTC, solarissmoke commented
If you look closely you'll see that the second argument is not `self`, so we need to retain the long-form version - `super()` would run the method on the wrong object.

2020-10-25 13:07 UTC, hartwork commented
> If you look closely you'll see that the second argument is not `self`, so we need to retain the long-form version - `super()` would run the method on the wrong object.

You're 100% right, sorry.

2020-10-25 13:07 UTC, hartwork approved these changes

2020-10-26 03:55 UTC, merged